version: '3'

services:
  nodejs:
    build: .
    image: danielesilva25/ubuntu-ssh-nvm:latest
    volumes:
      - .:/workspace
    ports:
      - "22"
      - "3090"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432"
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data


